name: workspace_root
description: flutter-app-template workspace root.
publish_to: none

environment:
  sdk: ^3.12.0

workspace:
  - app
  - features/auth
  - features/home
  - packages/core
  - packages/integrations
  - packages/localization
  - packages/permissions
  - packages/ui

dev_dependencies:
  very_good_analysis: ^10.3.0
